
name: CI/CD

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Ejecutar tests
        run: |
          python -m pytest

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: |
          docker build -t ghcr.io/jipuelma1521/scientific-api:latest .

      - name: Iniciar sesion en GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Publicar imagen Docker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/jipuelma1521/scientific-api:latest